
data:extend(
{
--Bateries
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-batteries",
        order = "Baa[b_mk5]",
        item_product = "b_mk5",
        amount = 100,
        steam_stats_name = "batteries-production-overall",
        icon = "__base__/graphics/icons/battery-mk2-equipment.png",
        icon_size = 64,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-batteries",
        order = "Bab[b_mk5]",
        item_product = "b_mk5",
        amount = 1000,
        steam_stats_name = "batteries-production-overall",
        icon = "__base__/graphics/icons/battery-mk2-equipment.png",
        icon_size = 64,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_3-100-batteries",
        order = "Bac[b_mk10]",
        item_product = "b_mk10",
        amount = 100,
        steam_stats_name = "batteries-production-overall",
        icon = "__base__/graphics/icons/battery-mk2-equipment.png",
        icon_size = 64,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_4-1000-batteries",
        order = "Bad[b_mk10]",
        item_product = "b_mk10",
        amount = 1000,
        steam_stats_name = "batteries-production-overall",
        icon = "__base__/graphics/icons/battery-mk2-equipment.png",
        icon_size = 64,
        limited_to_one_game = true,
    },
--Fusion
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-fusion",
        order = "Faa[f_mk5]",
        item_product = "f_mk5",
        amount = 100,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/equipment/hr-fusion-reactor-equipment.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-fusion",
        order = "Fab[f_mk5]",
        item_product = "f_mk5",
        amount = 1000,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/equipment/hr-fusion-reactor-equipment.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_3-100-fusion",
        order = "Fac[f_mk10]",
        item_product = "f_mk10",
        amount = 100,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/equipment/hr-fusion-reactor-equipment.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_4-1000-fusion",
        order = "Fad[f_mk10]",
        item_product = "f_mk10",
        amount = 1000,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/equipment/hr-fusion-reactor-equipment.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
--Shield
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-shield",
        order = "Saa[s_mk5]",
        item_product = "s_mk5",
        amount = 100,
        steam_stats_name = "shield-production-overall",
        icon = "__base__/graphics/equipment/hr-energy-shield-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-shield",
        order = "Sab[s_mk5]",
        item_product = "s_mk5",
        amount = 1000,
        steam_stats_name = "shield-production-overall",
        icon = "__base__/graphics/equipment/hr-energy-shield-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_3-100-shield",
        order = "Sac[s_mk10]",
        item_product = "s_mk10",
        amount = 100,
        steam_stats_name = "shield-production-overall",
        icon = "__base__/graphics/equipment/hr-energy-shield-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_4-1000-shield",
        order = "Sad[s_mk10]",
        item_product = "s_mk10",
        amount = 1000,
        steam_stats_name = "shield-production-overall",
        icon = "__base__/graphics/equipment/hr-energy-shield-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
--Armor
    {
        type = "produce-achievement",
        name = "i-have-friends",
        order = "Aaa[a_mk1]",
        item_product = "a_mk1",
        amount = 10,
        steam_stats_name = "armor-production-overall",
        icon = "__base__/graphics/technology/power-armor-mk2.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "i-have-friends-upgrade-1",
        order = "Aab[a_mk5]",
        item_product = "a_mk5",
        amount = 10,
        steam_stats_name = "armor-production-overall",
        icon = "__base__/graphics/technology/power-armor-mk2.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "i-have-friends-upgrade-2",
        order = "Aac[a_mk10]",
        item_product = "a_mk10",
        amount = 10,
        steam_stats_name = "armor-production-overall",
        icon = "__base__/graphics/technology/power-armor-mk2.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
--Damage
    {
        type = "player-damaged-achievement",
        name = "the-undying-1",
        order = "Caa[exploration]-g[golem]",
        should_survive = true,
        minimum_damage = 500000,
        steam_stats_name = "surived-damage-in-one-hit",
        icon = "__base__/graphics/achievement/golem.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "player-damaged-achievement",
        name = "the-undying-2",
        order = "Cab[exploration]-g[golem]",
        should_survive = true,
        minimum_damage = 1000000,
        steam_stats_name = "surived-damage-in-one-hit",
        icon = "__base__/graphics/achievement/golem.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "player-damaged-achievement",
        name = "the-undying-3",
        order = "Cac[exploration]-g[golem]",
        should_survive = true,
        minimum_damage = 5000000,
        steam_stats_name = "surived-damage-in-one-hit",
        icon = "__base__/graphics/achievement/golem.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
--roboport
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-roboport",
        order = "Raa[r_mk5]",
        item_product = "r_mk5",
        amount = 100,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-personal-roboport-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-roboport",
        order = "Rab[r_mk5]",
        item_product = "r_mk5",
        amount = 1000,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/equipment/hr-personal-roboport-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_1-100-roboport",
        order = "Rac[r_mk10]",
        item_product = "r_mk10",
        amount = 100,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-personal-roboport-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_2-1000-roboport",
        order = "Rad[r_mk10]",
        item_product = "r_mk10",
        amount = 1000,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-personal-roboport-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
--laser
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-laser",
        order = "Laa[l_mk5]",
        item_product = "l_mk5",
        amount = 100,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-personal-laser-defense-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-laser",
        order = "Lab[l_mk5]",
        item_product = "l_mk5",
        amount = 1000,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/equipment/hr-personal-laser-defense-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_1-100-laser",
        order = "Lac[l_mk10]",
        item_product = "l_mk10",
        amount = 100,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-personal-laser-defense-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_2-1000-laser",
        order = "Lad[l_mk10]",
        item_product = "l_mk10",
        amount = 1000,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-personal-laser-defense-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
--solar
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-solar",
        order = "PSaa[p-s_mk5]",
        item_product = "p-s_mk5",
        amount = 100,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-solar-panel-equipment.png",
        icon_size = 64,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-solar",
        order = "PSab[p-s_mk5]",
        item_product = "p-s_mk5",
        amount = 1000,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/equipment/hr-solar-panel-equipment.png",
        icon_size = 64,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_1-100-solar",
        order = "PSac[p-s_mk10]",
        item_product = "p-s_mk10",
        amount = 100,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-solar-panel-equipment.png",
        icon_size = 64,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_2-1000-solar",
        order = "PSad[p-s_mk10]",
        item_product = "p-s_mk10",
        amount = 1000,
        steam_stats_name = "roboport-production-overall",
        icon = "__base__/graphics/equipment/hr-solar-panel-equipment.png",
        icon_size = 64,
        limited_to_one_game = true,
    },
})
