Also this is where i specify item(s) completed
- 10 New armours added
- 10 New shields added.
- 10 New tiers batteries.
- 10 New tiers of fusion reactor
- 10 Personal solar
- 10 Roboport
- 10 Personal laser defense
- 5  Exoskeleton
- 2  NVG''s
- 2  Belt-immunity