
data:extend(
{
        --[[
--Bateries
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-batteries",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "b_mk5",
        amount = 100,
        steam_stats_name = "batteries-production-overall",
        icon = "__base__/graphics/achievement/Personal_battery_MK2_(research).png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-batteries",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "b_mk5",
        amount = 1000,
        steam_stats_name = "batteries-production-overall",
        icon = "__base__/graphics/achievement/Personal_battery_MK2_(research).png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2-1-100-batteries",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "b_mk10",
        amount = 100,
        steam_stats_name = "batteries-production-overall",
        icon = "__base__/graphics/achievement/Personal_battery_MK2_(research).png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_2-1000-batteries",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "b_mk10",
        amount = 1000,
        steam_stats_name = "batteries-production-overall",
        icon = "__base__/graphics/achievement/Personal_battery_MK2_(research).png",
        icon_size = 128,
        limited_to_one_game = true,
    },
--Fusion
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-fusion",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "f_mk5",
        amount = 100,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/achievement/Portable_fusion_reactor_(research).png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-fusion",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "f_mk5",
        amount = 1000,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/achievement/Portable_fusion_reactor_(research).png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2-1-100-fusion",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "f_mk10",
        amount = 100,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/achievement/Portable_fusion_reactor_(research).png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_2-1000-fusion",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "f_mk10",
        amount = 1000,
        steam_stats_name = "fusion-production-overall",
        icon = "__base__/graphics/achievement/Portable_fusion_reactor_(research).png",
        icon_size = 128,
        limited_to_one_game = true,
    },
--Shield
    {
        type = "produce-achievement",
        name = "mass-equipment-1_1-100-shield",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "s_mk5",
        amount = 100,
        steam_stats_name = "shield-production-overall",
        icon = "__base__/graphics/equipment/hr-energy-shield-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-1_2-1000-shield",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "s_mk5",
        amount = 1000,
        steam_stats_name = "shield-production-overall",
        icon = "__base__/graphics/equipment/hr-energy-shield-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2-1-100-shield",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "s_mk10",
        amount = 100,
        steam_stats_name = "shield-production-overall",
        icon = "__base__/graphics/equipment/hr-energy-shield-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "mass-equipment-2_2-1000-shield",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "s_mk10",
        amount = 1000,
        steam_stats_name = "shield-production-overall",
        icon = "__base__/graphics/equipment/hr-energy-shield-mk2-equipment.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
]]--
--Armor
    {
        type = "produce-achievement",
        name = "i-have-friends",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "a_mk1",
        amount = 5,
        steam_stats_name = "armor-production-overall",
        icon = "__base__/graphics/technology/power-armor-mk2.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "i-have-friends-upgrade-1",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "a_mk5",
        amount = 5,
        steam_stats_name = "armor-production-overall",
        icon = "__base__/graphics/technology/power-armor-mk2.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
    {
        type = "produce-achievement",
        name = "i-have-friends-upgrade-2",
        order = "d[production]-b[electronic-circuit-production]-a",
        item_product = "a_mk10",
        amount = 5,
        steam_stats_name = "armor-production-overall",
        icon = "__base__/graphics/technology/power-armor-mk2.png",
        icon_size = 256,
        limited_to_one_game = true,
    },
--Damage
    {
        type = "player-damaged-achievement",
        name = "the-undying-1",
        order = "b[exploration]-g[golem]",
        should_survive = true,
        minimum_damage = 500000000,
        steam_stats_name = "surived-damage-in-one-hit",
        icon = "__base__/graphics/achievement/golem.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
    {
        type = "player-damaged-achievement",
        name = "the-undying-2",
        order = "b[exploration]-g[golem]",
        should_survive = true,
        minimum_damage = 1500000000,
        steam_stats_name = "surived-damage-in-one-hit",
        icon = "__base__/graphics/achievement/golem.png",
        icon_size = 128,
        limited_to_one_game = true,
    },
})
