--compatibilities
	--require("compatibilities.recipes.armour_updates")
	--require("compatibilities.recipes.fusion_updates")
	--require("compatibilities.recipes.shield_updates")
--structures
	require("structures.compatibility-recipe-update")
	require("structures.science-setting")
	require("structures.altered-tech-updates")
	require("structures.mod-tech-prereq-updates")