--compatible.recipes
	require("mods.recipes.updates.armour_updates")
	require("mods.recipes.updates.batteries_updates")
	require("mods.recipes.updates.exolegs_updates")
	require("mods.recipes.updates.fission_updates")
	require("mods.recipes.updates.immunity_updates")
	require("mods.recipes.updates.lasers_updates")
	require("mods.recipes.updates.nvgs_updates")
	require("mods.recipes.updates.roboports_updates")
	require("mods.recipes.updates.shield_updates")
	require("mods.recipes.updates.solar_updates")
	require("mods.recipes.updates.compatible_updates")

--compatible.tech
	require("mods.technology.updates.par-depedency-updates")
	require("mods.technology.updates.spaceage-science-updates")
	require("mods.technology.updates.bobs-science-updates")
--structures
	require("structures.science-setting")
    --require("structures.tips_tricks.tips-a-tricks-updates")
    --require("structures.Milestones.preset_addons")
    --require("structures.Milestones.presets")