--compatibilities
	require("compatibilities.recipes.updates.armour_updates")
	require("compatibilities.recipes.updates.fusion_updates")
	require("compatibilities.recipes.updates.shield_updates")
	require("compatibilities.misc.compatibility-recipe-update")
	require("compatibilities.misc.altered-tech-updates")
	require("compatibilities.misc.mod-tech-prereq-updates")
--structures
	require("structures.science-setting")
