--[[
Have this one now modifed to work with my par mod. Tho i don't realy want this on my end as is the standard space age jsut without the armours.
Not sure if yours would need a forbidden_mods = {"Power-Armour-Replacer"} for it to work i think not any chnace to help/confirm this?
]]
if mods["Milestones"] then
    presets = {
        ["PARs SpaceAge Extension"] = {
            required_mods = {"space-age", "Power-Armour-Replacer", "PARs-SpaceAge-Extension"},
            milestones = {
                {type="group", name="Armour's"},
                {type="item",       name="par-armour-mk1",       quantity=1},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-armour-mk5",       quantity=1},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-armour-mk10",       quantity=1},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Batteries"},
                {type="item",       name="par-battery-mk1",       quantity=1},
                {type="item",       name="par-battery-mk1",       quantity=5},
                {type="item",       name="par-battery-mk1",       quantity=10},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-battery-mk5",       quantity=1},
                {type="item",       name="par-battery-mk5",       quantity=5},
                {type="item",       name="par-battery-mk5",       quantity=10},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-battery-mk10",       quantity=1},
                {type="item",       name="par-battery-mk10",       quantity=5},
                {type="item",       name="par-battery-mk10",       quantity=10},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Exo"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1},
                {type="item",       name="par-exoskeleton-mk1",       quantity=5},
                {type="item",       name="par-exoskeleton-mk1",       quantity=10},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1},
                {type="item",       name="par-exoskeleton-mk3",       quantity=5},
                {type="item",       name="par-exoskeleton-mk3",       quantity=10},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="legendary"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1},
                {type="item",       name="par-exoskeleton-mk5",       quantity=5},
                {type="item",       name="par-exoskeleton-mk5",       quantity=10},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="legendary"},

                {type="group", name="Fission reactor's"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1},
                {type="item",       name="par-fission-reactor-mk1",       quantity=5},
                {type="item",       name="par-fission-reactor-mk1",       quantity=10},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1},
                {type="item",       name="par-fission-reactor-mk5",       quantity=5},
                {type="item",       name="par-fission-reactor-mk5",       quantity=10},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1},
                {type="item",       name="par-fission-reactor-mk10",       quantity=5},
                {type="item",       name="par-fission-reactor-mk10",       quantity=10},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Night Imnmunity"},
                {type="item",       name="par-nightvision-mk1",       quantity=1},
                {type="item",       name="par-nightvision-mk2",       quantity=1},
                {type="item",       name="par-nightvision-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-nightvision-mk2",       quantity=1, quality="legendary"},

                {type="item",       name="par-belt-immunity-mk1",       quantity=1},
                {type="item",       name="par-belt-immunity-mk2",       quantity=1},
                {type="item",       name="par-belt-immunity-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-belt-immunity-mk2",       quantity=1, quality="legendary"},

                {type="group", name="Lasers"},
                {type="item",       name="par-laser-mk1",       quantity=1},
                {type="item",       name="par-laser-mk1",       quantity=5},
                {type="item",       name="par-laser-mk1",       quantity=10},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-laser-mk5",       quantity=1},
                {type="item",       name="par-laser-mk5",       quantity=5},
                {type="item",       name="par-laser-mk5",       quantity=10},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-laser-mk10",       quantity=1},
                {type="item",       name="par-laser-mk10",       quantity=5},
                {type="item",       name="par-laser-mk10",       quantity=10},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Roboports"},
                {type="item",       name="par-roboport-mk1",       quantity=1},
                {type="item",       name="par-roboport-mk1",       quantity=5},
                {type="item",       name="par-roboport-mk1",       quantity=10},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-roboport-mk5",       quantity=1},
                {type="item",       name="par-roboport-mk5",       quantity=5},
                {type="item",       name="par-roboport-mk5",       quantity=10},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-roboport-mk10",       quantity=1},
                {type="item",       name="par-roboport-mk10",       quantity=5},
                {type="item",       name="par-roboport-mk10",       quantity=10},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Shields"},
                {type="item",       name="par-shield-mk1",       quantity=1},
                {type="item",       name="par-shield-mk1",       quantity=5},
                {type="item",       name="par-shield-mk1",       quantity=10},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-shield-mk5",       quantity=1},
                {type="item",       name="par-shield-mk5",       quantity=5},
                {type="item",       name="par-shield-mk5",       quantity=10},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-shield-mk10",       quantity=1},
                {type="item",       name="par-shield-mk10",       quantity=5},
                {type="item",       name="par-shield-mk10",       quantity=10},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Solar panels"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1},
                {type="item",       name="par-solar-panel-mk1",       quantity=5},
                {type="item",       name="par-solar-panel-mk1",       quantity=10},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1},
                {type="item",       name="par-solar-panel-mk5",       quantity=5},
                {type="item",       name="par-solar-panel-mk5",       quantity=10},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1},
                {type="item",       name="par-solar-panel-mk10",       quantity=5},
                {type="item",       name="par-solar-panel-mk10",       quantity=10},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="legendary"},
            }
        },
        ["Space age"] = {
            required_mods = {"space-age", "Power-Armour-Replacer"},
            milestones = {
                {type="group",      name="Science"},
                {type="item",       name="automation-science-pack",      quantity=1},
                {type="item",       name="logistic-science-pack",        quantity=1},
                {type="item",       name="military-science-pack",        quantity=1},
                {type="item",       name="chemical-science-pack",        quantity=1},
                {type="item",       name="production-science-pack",      quantity=1},
                {type="item",       name="utility-science-pack",         quantity=1},
                {type="item",       name="space-science-pack",           quantity=1},
                {type="item",       name="metallurgic-science-pack",     quantity=1},
                {type="item",       name="electromagnetic-science-pack", quantity=1},
                {type="item",       name="agricultural-science-pack",    quantity=1},
                {type="item",       name="cryogenic-science-pack",       quantity=1},
                {type="item",       name="promethium-science-pack",      quantity=1},

                {type="group",      name="Science at scale"},
                {type="item",       name="automation-science-pack",      quantity=1000, next="x10"},
                {type="item",       name="logistic-science-pack",        quantity=1000, next="x10"},
                {type="item",       name="military-science-pack",        quantity=1000, next="x10"},
                {type="item",       name="chemical-science-pack",        quantity=1000, next="x10"},
                {type="item",       name="production-science-pack",      quantity=1000, next="x10"},
                {type="item",       name="utility-science-pack",         quantity=1000, next="x10"},
                {type="item",       name="space-science-pack",           quantity=1000, next="x10"},
                {type="item",       name="metallurgic-science-pack",     quantity=1000, next="x10"},
                {type="item",       name="electromagnetic-science-pack", quantity=1000, next="x10"},
                {type="item",       name="agricultural-science-pack",    quantity=1000, next="x10"},
                {type="item",       name="cryogenic-science-pack",       quantity=1000, next="x10"},
                {type="item",       name="promethium-science-pack",      quantity=1000, next="x10"},

                {type="group",      name="Progress"},
                {type="item",       name="locomotive",                  quantity=1},
                {type="fluid",      name="petroleum-gas",               quantity=1},
                {type="item",       name="construction-robot",          quantity=1},
                {type="item",       name="spidertron",                  quantity=1},
                {type="item_consumption", name="space-platform-starter-pack", quantity=1},
                {type="item_consumption", name="space-platform-starter-pack", quantity=10, next="x2"},
                {type="item",       name="foundry",                     quantity=1},
                {type="item",       name="biochamber",                  quantity=1},
                {type="item",       name="biolab",                      quantity=1},
                {type="item",       name="electromagnetic-plant",       quantity=1},
                {type="item",       name="cryogenic-plant",             quantity=1},
                {type="kill",       name="huge-promethium-asteroid",    quantity=1},

                {type="group",      name="Power"},
                {type="item",       name="solar-panel",             quantity=1},
                {type="item",       name="solar-panel",             quantity=1000, next="x10"},
                {type="item",       name="nuclear-reactor",         quantity=1},
                {type="item",       name="fusion-reactor",          quantity=1},

                {type="group",      name="Kills"},
                {type="kill",       name="medium-biter",            quantity=1},
                {type="kill",       name="big-biter",               quantity=1},
                {type="kill",       name="behemoth-biter",          quantity=1},
                {type="kill",       name="behemoth-biter",          quantity=1000, next="x10"},
                {type="kill",       name="small-strafer-pentapod",  quantity=1},
                {type="kill",       name="medium-strafer-pentapod", quantity=1},
                {type="kill",       name="big-strafer-pentapod",    quantity=1},
                {type="kill",       name="big-strafer-pentapod",    quantity=1000, next="x10"},
                {type="kill",       name="small-stomper-pentapod",  quantity=1},
                {type="kill",       name="medium-stomper-pentapod", quantity=1},
                {type="kill",       name="big-stomper-pentapod",    quantity=1},
                {type="kill",       name="big-stomper-pentapod",    quantity=1000, next="x10"},
                {type="kill",       name="small-demolisher",        quantity=1},
                {type="kill",       name="medium-demolisher",       quantity=1},
                {type="kill",       name="big-demolisher",          quantity=1},
                {type="kill",       name="big-demolisher",          quantity=10, next="x2"},
                {type="kill",       name="character",               quantity=1, next="x5", hidden=true},

                {type="group",      name="Quality"},
                {type="item",       name="quality-module",        quantity=1, quality="rare"},
                {type="item",       name="quality-module-2",      quantity=1, quality="rare"},
                {type="item",       name="quality-module-3",      quantity=1, quality="epic"},
                {type="item",       name="quality-module-3",      quantity=1, quality="legendary"},
                {type="item",       name="productivity-module-3", quantity=100, next="x10", quality="legendary"},
                {type="item",       name="spidertron",            quantity=1, quality="legendary"},
                {type="item",       name="raw-fish",              quantity=1, quality="legendary"},
            }
        },
    }
end