if mods["Milestones"] then
    preset_addons = {
        ["PA&R"] = {
            required_mods = {"Power-Armour-Replacer"},
            forbidden_mods = {"quality", "space-age", "PARs-SpaceAge-Extension"},
            milestones = {
                {type="group", name="Armour's"},
                {type="item",       name="par-armour-mk1",       quantity=1},
                {type="item",       name="par-armour-mk5",       quantity=1},
                {type="item",       name="par-armour-mk10",       quantity=1},

                {type="group", name="Batteries"},
                {type="item",       name="par-battery-mk1",       quantity=1},
                {type="item",       name="par-battery-mk1",       quantity=5},
                {type="item",       name="par-battery-mk1",       quantity=10},
                {type="item",       name="par-battery-mk5",       quantity=1},
                {type="item",       name="par-battery-mk5",       quantity=5},
                {type="item",       name="par-battery-mk5",       quantity=10},
                {type="item",       name="par-battery-mk10",       quantity=1},
                {type="item",       name="par-battery-mk10",       quantity=5},
                {type="item",       name="par-battery-mk10",       quantity=10},

                {type="group", name="Exo"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1},
                {type="item",       name="par-exoskeleton-mk1",       quantity=5},
                {type="item",       name="par-exoskeleton-mk1",       quantity=10},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1},
                {type="item",       name="par-exoskeleton-mk3",       quantity=5},
                {type="item",       name="par-exoskeleton-mk3",       quantity=10},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1},
                {type="item",       name="par-exoskeleton-mk5",       quantity=5},
                {type="item",       name="par-exoskeleton-mk5",       quantity=10},

                {type="group", name="Fission reactor's"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1},
                {type="item",       name="par-fission-reactor-mk1",       quantity=5},
                {type="item",       name="par-fission-reactor-mk1",       quantity=10},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1},
                {type="item",       name="par-fission-reactor-mk5",       quantity=5},
                {type="item",       name="par-fission-reactor-mk5",       quantity=10},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1},
                {type="item",       name="par-fission-reactor-mk10",       quantity=5},
                {type="item",       name="par-fission-reactor-mk10",       quantity=10},

                {type="group", name="Night Imnmunity"},
                {type="item",       name="par-nightvision-mk1",       quantity=1},
                {type="item",       name="par-nightvision-mk2",       quantity=1},

                {type="item",       name="par-belt-immunity-mk1",       quantity=1},
                {type="item",       name="par-belt-immunity-mk2",       quantity=1},

                {type="group", name="Lasers"},
                {type="item",       name="par-laser-mk1",       quantity=1},
                {type="item",       name="par-laser-mk1",       quantity=5},
                {type="item",       name="par-laser-mk1",       quantity=10},
                {type="item",       name="par-laser-mk5",       quantity=1},
                {type="item",       name="par-laser-mk5",       quantity=5},
                {type="item",       name="par-laser-mk5",       quantity=10},
                {type="item",       name="par-laser-mk10",       quantity=1},
                {type="item",       name="par-laser-mk10",       quantity=5},
                {type="item",       name="par-laser-mk10",       quantity=10},

                {type="group", name="Roboports"},
                {type="item",       name="par-roboport-mk1",       quantity=1},
                {type="item",       name="par-roboport-mk1",       quantity=5},
                {type="item",       name="par-roboport-mk1",       quantity=10},
                {type="item",       name="par-roboport-mk5",       quantity=1},
                {type="item",       name="par-roboport-mk5",       quantity=5},
                {type="item",       name="par-roboport-mk5",       quantity=10},
                {type="item",       name="par-roboport-mk10",       quantity=1},
                {type="item",       name="par-roboport-mk10",       quantity=5},
                {type="item",       name="par-roboport-mk10",       quantity=10},

                {type="group", name="Shields"},
                {type="item",       name="par-shield-mk1",       quantity=1},
                {type="item",       name="par-shield-mk1",       quantity=5},
                {type="item",       name="par-shield-mk1",       quantity=10},
                {type="item",       name="par-shield-mk5",       quantity=1},
                {type="item",       name="par-shield-mk5",       quantity=5},
                {type="item",       name="par-shield-mk5",       quantity=10},
                {type="item",       name="par-shield-mk10",       quantity=1},
                {type="item",       name="par-shield-mk10",       quantity=5},
                {type="item",       name="par-shield-mk10",       quantity=10},

                {type="group", name="Solar panels"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1},
                {type="item",       name="par-solar-panel-mk1",       quantity=5},
                {type="item",       name="par-solar-panel-mk1",       quantity=10},
                {type="item",       name="par-solar-panel-mk5",       quantity=1},
                {type="item",       name="par-solar-panel-mk5",       quantity=5},
                {type="item",       name="par-solar-panel-mk5",       quantity=10},
                {type="item",       name="par-solar-panel-mk10",       quantity=1},
                {type="item",       name="par-solar-panel-mk10",       quantity=5},
                {type="item",       name="par-solar-panel-mk10",       quantity=10},
            }
        },
        ["Quality PA&R"] = {
            required_mods = {"quality", "Power-Armour-Replacer"},
            forbidden_mods = {"space-age", "PARs-SpaceAge-Extension"},
            milestones = {
                {type="group", name="Armour's"},
                {type="item",       name="par-armour-mk1",       quantity=1},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-armour-mk5",       quantity=1},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-armour-mk10",       quantity=1},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Batteries"},
                {type="item",       name="par-battery-mk1",       quantity=1},
                {type="item",       name="par-battery-mk1",       quantity=5},
                {type="item",       name="par-battery-mk1",       quantity=10},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-battery-mk5",       quantity=1},
                {type="item",       name="par-battery-mk5",       quantity=5},
                {type="item",       name="par-battery-mk5",       quantity=10},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-battery-mk10",       quantity=1},
                {type="item",       name="par-battery-mk10",       quantity=5},
                {type="item",       name="par-battery-mk10",       quantity=10},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Exo"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1},
                {type="item",       name="par-exoskeleton-mk1",       quantity=5},
                {type="item",       name="par-exoskeleton-mk1",       quantity=10},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1},
                {type="item",       name="par-exoskeleton-mk3",       quantity=5},
                {type="item",       name="par-exoskeleton-mk3",       quantity=10},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="legendary"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1},
                {type="item",       name="par-exoskeleton-mk5",       quantity=5},
                {type="item",       name="par-exoskeleton-mk5",       quantity=10},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="legendary"},

                {type="group", name="Fission reactor's"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1},
                {type="item",       name="par-fission-reactor-mk1",       quantity=5},
                {type="item",       name="par-fission-reactor-mk1",       quantity=10},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1},
                {type="item",       name="par-fission-reactor-mk5",       quantity=5},
                {type="item",       name="par-fission-reactor-mk5",       quantity=10},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1},
                {type="item",       name="par-fission-reactor-mk10",       quantity=5},
                {type="item",       name="par-fission-reactor-mk10",       quantity=10},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Night Imnmunity"},
                {type="item",       name="par-nightvision-mk1",       quantity=1},
                {type="item",       name="par-nightvision-mk2",       quantity=1},
                {type="item",       name="par-nightvision-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-nightvision-mk2",       quantity=1, quality="legendary"},

                {type="item",       name="par-belt-immunity-mk1",       quantity=1},
                {type="item",       name="par-belt-immunity-mk2",       quantity=1},
                {type="item",       name="par-belt-immunity-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-belt-immunity-mk2",       quantity=1, quality="legendary"},

                {type="group", name="Lasers"},
                {type="item",       name="par-laser-mk1",       quantity=1},
                {type="item",       name="par-laser-mk1",       quantity=5},
                {type="item",       name="par-laser-mk1",       quantity=10},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-laser-mk5",       quantity=1},
                {type="item",       name="par-laser-mk5",       quantity=5},
                {type="item",       name="par-laser-mk5",       quantity=10},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-laser-mk10",       quantity=1},
                {type="item",       name="par-laser-mk10",       quantity=5},
                {type="item",       name="par-laser-mk10",       quantity=10},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Roboports"},
                {type="item",       name="par-roboport-mk1",       quantity=1},
                {type="item",       name="par-roboport-mk1",       quantity=5},
                {type="item",       name="par-roboport-mk1",       quantity=10},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-roboport-mk5",       quantity=1},
                {type="item",       name="par-roboport-mk5",       quantity=5},
                {type="item",       name="par-roboport-mk5",       quantity=10},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-roboport-mk10",       quantity=1},
                {type="item",       name="par-roboport-mk10",       quantity=5},
                {type="item",       name="par-roboport-mk10",       quantity=10},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Shields"},
                {type="item",       name="par-shield-mk1",       quantity=1},
                {type="item",       name="par-shield-mk1",       quantity=5},
                {type="item",       name="par-shield-mk1",       quantity=10},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-shield-mk5",       quantity=1},
                {type="item",       name="par-shield-mk5",       quantity=5},
                {type="item",       name="par-shield-mk5",       quantity=10},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-shield-mk10",       quantity=1},
                {type="item",       name="par-shield-mk10",       quantity=5},
                {type="item",       name="par-shield-mk10",       quantity=10},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Solar panels"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1},
                {type="item",       name="par-solar-panel-mk1",       quantity=5},
                {type="item",       name="par-solar-panel-mk1",       quantity=10},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1},
                {type="item",       name="par-solar-panel-mk5",       quantity=5},
                {type="item",       name="par-solar-panel-mk5",       quantity=10},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1},
                {type="item",       name="par-solar-panel-mk10",       quantity=5},
                {type="item",       name="par-solar-panel-mk10",       quantity=10},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="legendary"},
            }
        },
        ["Space PA&R"] = {
            required_mods = {"space-age", "quality", "Power-Armour-Replacer"},
            forbidden_mods = {"PARs-SpaceAge-Extension"},
            milestones = {
                {type="group", name="Armour's"},
                {type="item",       name="mech-armor",            quantity=1},
                {type="item",       name="mech-armor",            quantity=1, quality="rare"},
                {type="item",       name="mech-armor",            quantity=1, quality="epic"},
                {type="item",       name="mech-armor",            quantity=1, quality="legendary"},
                {type="item",       name="par-armour-mk1",       quantity=1},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-armour-mk5",       quantity=1},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-armour-mk10",       quantity=1},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-armour-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Batteries"},
                {type="item",       name="par-battery-mk1",       quantity=1},
                {type="item",       name="par-battery-mk1",       quantity=5},
                {type="item",       name="par-battery-mk1",       quantity=10},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-battery-mk5",       quantity=1},
                {type="item",       name="par-battery-mk5",       quantity=5},
                {type="item",       name="par-battery-mk5",       quantity=10},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-battery-mk10",       quantity=1},
                {type="item",       name="par-battery-mk10",       quantity=5},
                {type="item",       name="par-battery-mk10",       quantity=10},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-battery-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Exo"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1},
                {type="item",       name="par-exoskeleton-mk1",       quantity=5},
                {type="item",       name="par-exoskeleton-mk1",       quantity=10},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1},
                {type="item",       name="par-exoskeleton-mk3",       quantity=5},
                {type="item",       name="par-exoskeleton-mk3",       quantity=10},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk3",       quantity=1, quality="legendary"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1},
                {type="item",       name="par-exoskeleton-mk5",       quantity=5},
                {type="item",       name="par-exoskeleton-mk5",       quantity=10},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-exoskeleton-mk5",       quantity=1, quality="legendary"},

                {type="group", name="Fission reactor's"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1},
                {type="item",       name="par-fission-reactor-mk1",       quantity=5},
                {type="item",       name="par-fission-reactor-mk1",       quantity=10},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1},
                {type="item",       name="par-fission-reactor-mk5",       quantity=5},
                {type="item",       name="par-fission-reactor-mk5",       quantity=10},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1},
                {type="item",       name="par-fission-reactor-mk10",       quantity=5},
                {type="item",       name="par-fission-reactor-mk10",       quantity=10},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-fission-reactor-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Night Imnmunity"},
                {type="item",       name="par-nightvision-mk1",       quantity=1},
                {type="item",       name="par-nightvision-mk2",       quantity=1},
                {type="item",       name="par-nightvision-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-nightvision-mk2",       quantity=1, quality="legendary"},

                {type="item",       name="par-belt-immunity-mk1",       quantity=1},
                {type="item",       name="par-belt-immunity-mk2",       quantity=1},
                {type="item",       name="par-belt-immunity-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-belt-immunity-mk2",       quantity=1, quality="legendary"},

                {type="group", name="Lasers"},
                {type="item",       name="par-laser-mk1",       quantity=1},
                {type="item",       name="par-laser-mk1",       quantity=5},
                {type="item",       name="par-laser-mk1",       quantity=10},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-laser-mk5",       quantity=1},
                {type="item",       name="par-laser-mk5",       quantity=5},
                {type="item",       name="par-laser-mk5",       quantity=10},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-laser-mk10",       quantity=1},
                {type="item",       name="par-laser-mk10",       quantity=5},
                {type="item",       name="par-laser-mk10",       quantity=10},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-laser-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Roboports"},
                {type="item",       name="par-roboport-mk1",       quantity=1},
                {type="item",       name="par-roboport-mk1",       quantity=5},
                {type="item",       name="par-roboport-mk1",       quantity=10},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-roboport-mk5",       quantity=1},
                {type="item",       name="par-roboport-mk5",       quantity=5},
                {type="item",       name="par-roboport-mk5",       quantity=10},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-roboport-mk10",       quantity=1},
                {type="item",       name="par-roboport-mk10",       quantity=5},
                {type="item",       name="par-roboport-mk10",       quantity=10},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-roboport-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Shields"},
                {type="item",       name="par-shield-mk1",       quantity=1},
                {type="item",       name="par-shield-mk1",       quantity=5},
                {type="item",       name="par-shield-mk1",       quantity=10},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-shield-mk5",       quantity=1},
                {type="item",       name="par-shield-mk5",       quantity=5},
                {type="item",       name="par-shield-mk5",       quantity=10},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-shield-mk10",       quantity=1},
                {type="item",       name="par-shield-mk10",       quantity=5},
                {type="item",       name="par-shield-mk10",       quantity=10},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-shield-mk10",       quantity=1, quality="legendary"},

                {type="group", name="Solar panels"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1},
                {type="item",       name="par-solar-panel-mk1",       quantity=5},
                {type="item",       name="par-solar-panel-mk1",       quantity=10},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk1",       quantity=1, quality="legendary"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1},
                {type="item",       name="par-solar-panel-mk5",       quantity=5},
                {type="item",       name="par-solar-panel-mk5",       quantity=10},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk5",       quantity=1, quality="legendary"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1},
                {type="item",       name="par-solar-panel-mk10",       quantity=5},
                {type="item",       name="par-solar-panel-mk10",       quantity=10},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="rare"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="epic"},
                {type="item",       name="par-solar-panel-mk10",       quantity=1, quality="legendary"},
            }
        },
    }
end