require("prototypes.armour_recipes")
require("prototypes.batteries_recipes")
require("prototypes.fusion_recipes")
require("prototypes.legs_recipes")
require("prototypes.shield_recipes")
require("the-rest_recipes")