require("prototypes.armour_recipes")
require("prototypes.batteries_recipes")
require("prototypes.fusion_recipes")
--require("prototypes.legs_recipes")
require("prototypes.shield_recipes")
--require("prototypes.the-rest_recipes")
require("prototypes.item")
require("prototype.achievements")