local recipes = {
    {
        type = "recipe",
        name = "par-armour-mk1",
        categories = {"par-electronic-hands"},
        enabled = false,
        energy_required = 50.0,
        ingredients = {
            {type="item", name="heavy-armor", amount=1},
            {type="item", name="wood", amount=25},
            {type="item", name="stone-brick", amount=25},
            {type="item", name="steel-plate", amount=25},
            {type="item", name="electronic-circuit", amount=25},
        },
        results = {{type="item", name="par-armour-mk1", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk2",
        categories = {"par-electronic-hands"},
        enabled = false,
        energy_required = 50.0,
        ingredients = {
            {type="item", name="par-armour-mk1", amount=1},
            {type="item", name="wood", amount=50},
            {type="item", name="iron-plate", amount=50},
            {type="item", name="steel-plate", amount=50},
            {type="item", name="copper-plate", amount=50},
            {type="item", name="electronic-circuit", amount=50},
        },
        results = {{type="item", name="par-armour-mk2", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk3",
        categories = {"par-electronic-hands"},
        enabled = false,
        energy_required = 50.0,
        ingredients = {
            {type="item", name="par-armour-mk2", amount=1},
            {type="item", name="plastic-bar", amount=75},
            {type="item", name="steel-plate", amount=75},
            {type="item", name="engine-unit", amount=75},
            {type="item", name="advanced-circuit", amount=75},
        },
        results = {{type="item", name="par-armour-mk3", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk4",
        categories = {"par-electronic-hands"},
        enabled = false,
        energy_required = 50.0,
        ingredients = {
            {type="item", name="par-armour-mk3", amount=1},
            {type="item", name="steel-plate", amount=100},
            {type="item", name="engine-unit", amount=100},
            {type="item", name="plastic-bar", amount=100},
            {type="item", name="advanced-circuit", amount=100},
            {type="item", name="electric-engine-unit", amount=100},
        },
        results = {{type="item", name="par-armour-mk4", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk5",
        categories = {"par-electronic-hands"},
        enabled = false,
        energy_required = 50.0,
        ingredients = {
            {type="item", name="par-armour-mk4", amount=1},
            {type="item", name="battery", amount=150},
            {type="item", name="advanced-circuit", amount=150},
            {type="item", name="armour-control-unit", amount=150},
            {type="item", name="electric-engine-unit", amount=150},
        },
        results = {{type="item", name="par-armour-mk5", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk6",
        categories= {"par-electronics"},
        enabled = false,
        energy_required = 10.0,
        ingredients = {
            {type="item", name="par-armour-mk5", amount=1},
            {type="item", name="steel-plate", amount=200},
            {type="item", name="copper-plate", amount=200},
            {type="item", name="processing-unit", amount=200},
            {type="item", name="armour-control-unit", amount=200},
            {type="fluid", name="petroleum-gas", amount=200},
        },
        results = {{type="item", name="par-armour-mk6", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk7",
        categories={"par-electronics"},
        enabled = false,
        energy_required = 10.0,
        ingredients = {
            {type="item", name="par-armour-mk6", amount=1},
            {type="item", name="steel-plate", amount=400},
            {type="item", name="processing-unit", amount=400},
            {type="item", name="uranium-fuel-cell", amount=400},
            {type="item", name="low-density-structure", amount=400},
            {type="fluid", name="petroleum-gas", amount=400},
        },
        results = {{type="item", name="par-armour-mk7", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk8",
        categories={"par-electronics"},
        enabled = false,
        energy_required = 10.0,
        ingredients = {
            {type="item", name="par-armour-mk7", amount=1},
            {type="item", name="battery", amount=600},
            {type="item", name="nuclear-fuel", amount=600},
            {type="item", name="processing-unit", amount=600},
            {type="item", name="low-density-structure", amount=600},
            {type="fluid", name="lubricant", amount=600},
        },
        results = {{type="item", name="par-armour-mk8", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk9",
        categories={"par-electronics"},
        enabled = false,
        energy_required = 10.0,
        ingredients = {
            {type="item", name="par-armour-mk8", amount=1},
            {type="item", name="nuclear-fuel", amount=800},
            {type="item", name="processing-unit", amount=800},
            {type="item", name="armour-control-unit", amount=800},
            {type="item", name="low-density-structure", amount=800},
            {type="fluid", name="lubricant", amount=800},
        },
        results = {{type="item", name="par-armour-mk9", amount=1}},
    },
    {
        type = "recipe",
        name = "par-armour-mk10",
        categories={"par-electronics"},
        enabled = false,
        energy_required = 10.0,
        ingredients = {
            {type="item", name="par-armour-mk9", amount=1},
            {type="item", name="nuclear-fuel", amount=1000},
            {type="item", name="processing-unit", amount=1000},
            {type="item", name="armour-control-unit", amount=1000},
            {type="item", name="low-density-structure", amount=1000},
            {type="fluid", name="lubricant", amount=1000},
        },
        results = {{type="item", name="par-armour-mk10", amount=1}},
    },
}
data:extend(recipes)
if mods["space-age"] then
    data:extend({
        {
            type = "recipe",
            name = "par-armour-mk1",
            categories = {"par-electronic-hands"},
            allow_decomposition = true,
            enabled = false,
            energy_required = 50.0,
            ingredients = {
                {type="item", name="heavy-armor", amount=1},
                {type="item", name="electronic-circuit", amount=25},
                {type="item", name="stone-brick", amount=25},
                {type="item", name="steel-plate", amount=25},
                {type="item", name="wood", amount=25},
            },
            results = {{type="item", name="par-armour-mk1", amount=1}},
        },
        {
            type = "recipe",
            name = "par-armour-mk2",
            categories = {"par-electronic-hands"},
            allow_decomposition = true,
            enabled = false,
            energy_required = 50.0,
            ingredients = {
                {type="item", name="par-armour-mk1", amount=1},
                {type="item", name="electronic-circuit", amount=50},
                {type="item", name="copper-plate", amount=50},
                {type="item", name="steel-plate", amount=50},
                {type="item", name="iron-plate", amount=50},
                {type="item", name="wood", amount=50},
            },
            results = {{type="item", name="par-armour-mk2", amount=1}},
        },
        {
            type = "recipe",
            name = "par-armour-mk3",
            categories = {"par-electronic-hands"},
            allow_decomposition = true,
            enabled = false,
            energy_required = 50.0,
            ingredients = {
                {type="item", name="par-armour-mk2", amount=1},
                {type="item", name="advanced-circuit", amount=75},
                {type="item", name="plastic-bar", amount=75},
                {type="item", name="steel-plate", amount=75},
                {type="item", name="engine-unit", amount=75},
            },
            results = {{type="item", name="par-armour-mk3", amount=1}},
        },
        {
            type = "recipe",
            name = "par-armour-mk4",
            categories = {"par-electronic-hands"},
            allow_decomposition = true,
            enabled = false,
            energy_required = 50.0,
            ingredients = {
                {type="item", name="par-armour-mk3", amount=1},
                {type="item", name="electric-engine-unit", amount=100},
                {type="item", name="advanced-circuit", amount=100},
                {type="item", name="steel-plate", amount=100},
                {type="item", name="engine-unit", amount=100},
                {type="item", name="plastic-bar", amount=100},
            },
            results = {{type="item", name="par-armour-mk4", amount=1}},
        },
        {
            type = "recipe",
            name = "par-armour-mk5",
            categories = {"par-electronic-hands"},
            enabled = false,
            energy_required = 50.0,
            ingredients = {
                {type="item", name="par-armour-mk4", amount=1},
                {type="item", name="armour-control-unit", amount=150},
                {type="item", name="electric-engine-unit", amount=150},
                {type="item", name="processing-unit", amount=150},
                {type="item", name="battery", amount=150},
                {type="item", name="carbon", amount=150},
            },
            results = {{type="item", name="par-armour-mk5", amount=1}},
        },
        {
            type = "recipe",
            name = "par-armour-mk6",
            categories = {"par-electronics"},
            enabled = false,
            energy_required = 10.0,
            ingredients = {
                {type="item", name="par-armour-mk5", amount=1},
                {type="item", name="electric-engine-unit", amount=200},
                {type="item", name="armour-control-unit", amount=200},
                {type="item", name="processing-unit", amount=200},
                {type="item", name="tungsten-plate", amount=200},
                {type="item", name="holmium-plate", amount=200},
                {type="item", name="carbon-fiber", amount=200},
            },
            results = {{type="item", name="par-armour-mk6", amount=1}},
        },
        {
            type = "recipe",
            name = "par-armour-mk7",
            categories = {"par-electronics"},
            enabled = false,
            energy_required = 10.0,
            ingredients = {
                {type="item", name="par-armour-mk6", amount=1},
                {type="item", name="low-density-structure", amount=400},
                {type="item", name="armour-control-unit", amount=400},
                {type="item", name="processing-unit", amount=400},
                {type="item", name="tungsten-plate", amount=400},
                {type="item", name="supercapacitor", amount=400},
                {type="item", name="lithium-plate", amount=400},
                --fluids
                {type="fluid", name="electrolyte", amount=400},
                {type="fluid", name="ammonia", amount=400},
            },
            results = {{type="item", name="par-armour-mk7", amount=1}},
        },
        {
            type = "recipe",
            name = "par-armour-mk8",
            categories = {"par-electronics"},
            enabled = false,
            energy_required = 10.0,
            ingredients = {
                {type="item", name="par-armour-mk7", amount=1},
                {type="item", name="low-density-structure", amount=600},
                {type="item", name="armour-control-unit", amount=600},
                {type="item", name="tungsten-plate", amount=600},
                {type="item", name="quantum-processor", amount=600},
                {type="item", name="supercapacitor", amount=600},
                {type="item", name="lithium-plate", amount=600},
                {type="item", name="carbon-fiber", amount=600},
                {type="item", name="battery", amount=600},
                --fluids
                {type="fluid", name="electrolyte", amount=600},
                {type="fluid", name="ammonia", amount=600},
            },
            results = {{type="item", name="par-armour-mk8", amount=1}},
        },
        {
            type = "recipe",
            name = "par-armour-mk9",
            main_product = "par-armour-mk9",
            categories = {"par-electronics"},
            enabled = false,
            energy_required = 10.0,
            ingredients = {
                {type="item", name="par-armour-mk8", amount=1},
                {type="item", name="low-density-structure", amount=800},
                {type="item", name="armour-control-unit", amount=800},
                {type="item", name="quantum-processor", amount=800},
                {type="item", name="tungsten-carbide", amount=800},
                {type="item", name="tungsten-plate", amount=800},
                {type="item", name="supercapacitor", amount=800},
                {type="item", name="superconductor", amount=800},
                {type="item", name="lithium-plate", amount=800},
                {type="item", name="carbon-fiber", amount=800},
                {type="item", name="biter-egg", amount=800},
                --fluids
                {type="fluid", name="fluoroketone-cold", amount=800},
                {type="fluid", name="electrolyte", amount=800},
            },
            results = {
                {type="item", name="par-armour-mk9", amount=1},
                {type="fluid", name="fluoroketone-hot", amount=700},
            },
        },
        {
            type = "recipe",
            name = "par-armour-mk10",
            main_product = "par-armour-mk10",
            categories = {"par-electronics"},
            enabled = false,
            energy_required = 10.0,
            ingredients = {
                {type="item", name="par-armour-mk9", amount=1},
                {type="item", name="low-density-structure", amount=1000},
                {type="item", name="armour-control-unit", amount=1000},
                {type="item", name="quantum-processor", amount=1000},
                {type="item", name="tungsten-carbide", amount=1000},
                {type="item", name="tungsten-plate", amount=1000},
                {type="item", name="supercapacitor", amount=1000},
                {type="item", name="superconductor", amount=1000},
                {type="item", name="holmium-plate", amount=1000},
                {type="item", name="lithium-plate", amount=1000},
                {type="item", name="carbon-fiber", amount=1000},
                {type="item", name="biter-egg", amount=1000},
                --fluids
                {type="fluid", name="electrolyte", amount=1000},
                {type="fluid", name="fluoroketone-cold", amount=1000},
            },
            results = {
                {type="item", name="par-armour-mk10", amount=1},
                {type="fluid", name="fluoroketone-hot", amount=900},
            },
        },
    })
end
