data:extend({
    {
        type = "recipe",
        name = "par-fission-reactor-mk1",
        enabled = false,
        energy_required = 40,
        ingredients = {
            {type="item", name="electronic-circuit", amount=50},
            {type="item", name="steel-plate", amount=100},
            {type="item", name="copper-plate", amount=100},
            {type="item", name="stone-brick", amount=50},
        },
        results = {{type="item", name="par-fission-reactor-mk1", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk2",
        enabled = false,
        energy_required = 45,
        ingredients = {
            {type="item", name="par-fission-reactor-mk1", amount=1},
            {type="item", name="iron-plate", amount=95},
            {type="item", name="copper-cable", amount=165},
            {type="item", name="electronic-circuit", amount=60},
        },
        results = {{type="item", name="par-fission-reactor-mk2", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk3",
        enabled = false,
        energy_required = 50,
        ingredients = {
            {type="item", name="par-fission-reactor-mk2", amount=1},
            {type="item", name="battery", amount=10},
            {type="item", name="electronic-circuit", amount=120},
            {type="item", name="solid-fuel", amount=50},
        },
        results = {{type="item", name="par-fission-reactor-mk3", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk4",
        enabled = false,
        energy_required = 55,
        ingredients = {
            {type="item", name="par-fission-reactor-mk3", amount=1},
            {type="item", name="advanced-circuit", amount=20},
            {type="item", name="copper-plate", amount=50},
            {type="item", name="engine-unit", amount=40},
            {type="item", name="steel-plate", amount=100},
        },
        results = {{type="item", name="par-fission-reactor-mk4", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk5",
        enabled = false,
        energy_required = 60,
        ingredients = {
            {type="item", name="par-fission-reactor-mk4", amount=1},
            {type="item", name="battery", amount=20},
            {type="item", name="plastic-bar", amount=50},
            {type="item", name="engine-unit", amount=50},
            {type="item", name="advanced-circuit", amount=50},
        },
        results = {{type="item", name="par-fission-reactor-mk5", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk6",
        enabled = false,
        energy_required = 65,
        ingredients = {
            {type="item", name="par-fission-reactor-mk5", amount=1},
            {type="item", name="plastic-bar", amount=100},
            {type="item", name="processing-unit", amount=50},
            {type="item", name="advanced-circuit", amount=80},
            {type="item", name="uranium-fuel-cell", amount=100},
            {type="item", name="electric-engine-unit", amount=65},
        },
        results = {{type="item", name="par-fission-reactor-mk6", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk7",
        enabled = false,
        energy_required = 70,
        ingredients = {
            {type="item", name="par-fission-reactor-mk6", amount=1},
            {type="item", name="electric-engine-unit", amount=100},
            {type="item", name="processing-unit", amount=50},
            {type="item", name="advanced-circuit", amount=100},
            {type="item", name="pipe", amount=80},
        },
        results = {{type="item", name="par-fission-reactor-mk7", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk8",
        enabled = false,
        energy_required = 75,
        ingredients = {
            {type="item", name="par-fission-reactor-mk7", amount=1},
            {type="item", name="sulfur", amount=50},
            {type="item", name="advanced-circuit", amount=100},
            {type="item", name="processing-unit", amount=100},
            {type="item", name="low-density-structure", amount=100},
        },
        results = {{type="item", name="par-fission-reactor-mk8", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk9",
        category = "crafting-with-fluid",
        enabled = false,
        energy_required = 80,
        ingredients = {
            {type="item", name="par-fission-reactor-mk8", amount=1},
            {type="item", name="nuclear-fuel", amount=55},
            {type="item", name="processing-unit", amount=150},
            {type="item", name="armour-control-unit", amount=30},
            {type="item", name="low-density-structure", amount=250},
            {type="fluid", name="petroleum-gas", amount=200}
        },
        results = {{type="item", name="par-fission-reactor-mk9", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fission-reactor-mk10",
        enabled = false,
        energy_required = 85,
        ingredients = {
            {type="item", name="par-fission-reactor-mk9", amount=1},
            {type="item", name="battery", amount=100},
            {type="item", name="processing-unit", amount=200},
            {type="item", name="armour-control-unit", amount=30},
            {type="item", name="low-density-structure", amount=250},
        },
        results = {{type="item", name="par-fission-reactor-mk10", amount=1}},
    },
})

if mods["space-age"] then
    data:extend({
        {
            type = "recipe",
            name = "par-fission-reactor-mk1",
            category = "electronics-or-handcrafting",
            enabled = false,
            energy_required = 40,
            ingredients = {
                {type="item", name="electronic-circuit", amount=25},
                {type="item", name="copper-plate", amount=25},
                {type="item", name="steel-plate", amount=25},
                {type="item", name="iron-plate", amount=25},
                {type="item", name="wood", amount=25},
            },
            results = {{type="item", name="par-fission-reactor-mk1", amount=1}},
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk2",
            category = "electronics-or-handcrafting",
            enabled = false,
            energy_required = 45,
            ingredients = {
                {type="item", name="par-fission-reactor-mk1", amount=1},
                {type="item", name="electronic-circuit", amount=50},
                {type="item", name="copper-plate", amount=50},
                {type="item", name="steel-plate", amount=50},
                {type="item", name="iron-plate", amount=50},
            },
            results = {{type="item", name="par-fission-reactor-mk2", amount=1}},
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk3",
            category = "electronics-or-handcrafting",
            enabled = false,
            energy_required = 50,
            ingredients = {
                {type="item", name="par-fission-reactor-mk2", amount=1},
                {type="item", name="advanced-circuit", amount=75},
                {type="item", name="plastic-bar", amount=75},
                {type="item", name="engine-unit", amount=75},
                {type="item", name="battery", amount=75},
            },
            results = {{type="item", name="par-fission-reactor-mk3", amount=1}},
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk4",
            category = "electronics-or-handcrafting",
            enabled = false,
            energy_required = 55,
            ingredients = {
                {type="item", name="par-fission-reactor-mk3", amount=1},
                {type="item", name="advanced-circuit", amount=100},
                {type="item", name="plastic-bar", amount=100},
                {type="item", name="engine-unit", amount=100},
                {type="item", name="battery", amount=100},
            },
            results = {{type="item", name="par-fission-reactor-mk4", amount=1}},
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk5",
            category = "electronics-or-handcrafting",
            enabled = false,
            energy_required = 60,
            ingredients = {
                {type="item", name="par-fission-reactor-mk4", amount=1},
                {type="item", name="electric-engine-unit", amount=125},
                {type="item", name="advanced-circuit", amount=125},
                {type="item", name="plastic-bar", amount=125},
                {type="item", name="battery", amount=125},
                {type="item", name="carbon", amount=125},
            },
            results = {{type="item", name="par-fission-reactor-mk5", amount=1}},
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk6",
            category = "electronics",
            enabled = false,
            energy_required = 65,
            ingredients = {
                {type="item", name="par-fission-reactor-mk5", amount=1},
                {type="item", name="electric-engine-unit", amount=150},
                {type="item", name="processing-unit", amount=150},
                {type="item", name="superconductor", amount=150},
                {type="item", name="supercapacitor", amount=150},
                {type="item", name="holmium-plate", amount=150},
                {type="item", name="carbon", amount=150},
            },
            results = {{type="item", name="par-fission-reactor-mk6", amount=1}},
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk7",
            category = "electronics",
            enabled = false,
            energy_required = 70,
            ingredients = {
                {type="item", name="par-fission-reactor-mk6", amount=1},
                {type="item", name="electric-engine-unit", amount=200},
                {type="item", name="processing-unit", amount=200},
                {type="item", name="superconductor", amount=200},
                {type="item", name="supercapacitor", amount=200},
                {type="item", name="holmium-plate", amount=200},
                {type="item", name="tungsten-plate", amount=200},
                {type="item", name="lithium-plate", amount=200},

                {type="fluid", name="lubricant", amount=250},
                {type="fluid", name="electrolyte", amount=250},
            },
            results = {{type="item", name="par-fission-reactor-mk7", amount=1}},
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk8",
            category = "electronics",
            enabled = false,
            energy_required = 75,
            ingredients = {
                {type="item", name="par-fission-reactor-mk7", amount=1},
                {type="item", name="low-density-structure", amount=300},
                {type="item", name="armour-control-unit", amount=300},
                {type="item", name="quantum-processor", amount=300},
                {type="item", name="tungsten-carbide", amount=300},
                {type="item", name="tungsten-plate", amount=300},
                {type="item", name="superconductor", amount=300},
                {type="item", name="holmium-plate", amount=300},
                {type="item", name="lithium-plate", amount=300},
                {type="item", name="supercapacitor", amount=300},
                {type="item", name="carbon-fiber", amount=300},

                {type="fluid", name="lubricant", amount=250},
                {type="fluid", name="electrolyte", amount=250},
            },
            results = {{type="item", name="par-fission-reactor-mk8", amount=1}},
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk9",
            main_product = "par-fission-reactor-mk9",
            category = "electronics",
            enabled = false,
            energy_required = 80,
            ingredients = {
                {type="item", name="par-fission-reactor-mk8", amount=1},
                {type="item", name="low-density-structure", amount=400},
                {type="item", name="armour-control-unit", amount=400},
                {type="item", name="quantum-processor", amount=400},
                {type="item", name="tungsten-carbide", amount=400},
                {type="item", name="tungsten-plate", amount=400},
                {type="item", name="superconductor", amount=400},
                {type="item", name="holmium-plate", amount=400},
                {type="item", name="supercapacitor", amount=400},
                {type="item", name="lithium-plate", amount=400},
                {type="item", name="carbon-fiber", amount=400},
                {type="item", name="biter-egg", amount=400},
                --Fluid
                {type="fluid", name="electrolyte", amount=250},
                {type="fluid", name="fluoroketone-cold", amount=100},
            },
            results = {
                {type="item", name="par-fission-reactor-mk9", amount=1},
                {type="fluid", name="fluoroketone-hot", amount=100},
            },
        },
        {
            type = "recipe",
            name = "par-fission-reactor-mk10",
            main_product = "par-fission-reactor-mk10",
            category = "electronics",
            enabled = false,
            energy_required = 85,
            ingredients = {
                {type="item", name="par-fission-reactor-mk9", amount=1},
                {type="item", name="low-density-structure", amount=500},
                {type="item", name="armour-control-unit", amount=500},
                {type="item", name="quantum-processor", amount=500},
                {type="item", name="tungsten-carbide", amount=500},
                {type="item", name="tungsten-plate", amount=500},
                {type="item", name="superconductor", amount=500},
                {type="item", name="holmium-plate", amount=500},
                {type="item", name="carbon-fiber", amount=500},
                {type="item", name="supercapacitor", amount=500},
                {type="item", name="lithium-plate", amount=500},
                {type="item", name="biter-egg", amount=500},
                --Fluid
                {type="fluid", name="electrolyte", amount=250},
                {type="fluid", name="fluoroketone-cold", amount=200},
            },
            results = {
                {type="item", name="par-fission-reactor-mk10", amount=1},
                {type="fluid", name="fluoroketone-hot", amount=200},
            },
        },
    })
end