local recipes = {
    {
        type = "recipe",
        name = "par-fusion-reactor-mk1",
        enabled = false,
        energy_required = 40,
        ingredients = {
            {type="item", name="electronic-circuit", amount=50},
            {type="item", name="steel-plate", amount=100},
            {type="item", name="copper-plate", amount=100},
            {type="item", name="stone-brick", amount=50},
        },
        results = {{type="item", name="par-fusion-reactor-mk1", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk2",
        enabled = false,
        energy_required = 45,
        ingredients = {
            {type="item", name="par-fusion-reactor-mk1", amount=1},
            {type="item", name="iron-plate", amount=95},
            {type="item", name="copper-cable", amount=165},
            {type="item", name="electronic-circuit", amount=60},
        },
        results = {{type="item", name="par-fusion-reactor-mk2", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk3",
        enabled = false,
        energy_required = 50,
        ingredients = {
            {type="item", name="par-fusion-reactor-mk2", amount=1},
            {type="item", name="battery", amount=10},
            {type="item", name="electronic-circuit", amount=120},
            {type="item", name="solid-fuel", amount=50},
        },
        results = {{type="item", name="par-fusion-reactor-mk3", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk4",
        enabled = false,
        energy_required = 55,
        ingredients = {
            {type="item", name="par-fusion-reactor-mk3", amount=1},
            {type="item", name="advanced-circuit", amount=20},
            {type="item", name="copper-plate", amount=50},
            {type="item", name="engine-unit", amount=40},
            {type="item", name="steel-plate", amount=100},
        },
        results = {{type="item", name="par-fusion-reactor-mk4", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk5",
        enabled = false,
        energy_required = 60,
        ingredients = {
            {type="item", name="par-fusion-reactor-mk4", amount=1},
            {type="item", name="battery", amount=20},
            {type="item", name="plastic-bar", amount=50},
            {type="item", name="engine-unit", amount=50},
            {type="item", name="advanced-circuit", amount=50},
        },
        results = {{type="item", name="par-fusion-reactor-mk5", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk6",
        enabled = false,
        energy_required = 65,
        hide_from_player_crafting = true,
        ingredients = {
            {type="item", name="par-fusion-reactor-mk5", amount=1},
            {type="item", name="plastic-bar", amount=100},
            {type="item", name="processing-unit", amount=50},
            {type="item", name="advanced-circuit", amount=80},
            {type="item", name="uranium-fuel-cell", amount=100},
            {type="item", name="electric-engine-unit", amount=65},
        },
        results = {{type="item", name="par-fusion-reactor-mk6", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk7",
        enabled = false,
        energy_required = 70,
        hide_from_player_crafting = true,
        ingredients = {
            {type="item", name="par-fusion-reactor-mk6", amount=1},
            {type="item", name="electric-engine-unit", amount=100},
            {type="item", name="processing-unit", amount=50},
            {type="item", name="advanced-circuit", amount=100},
            {type="item", name="pipe", amount=80},
        },
        results = {{type="item", name="par-fusion-reactor-mk7", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk8",
        enabled = false,
        energy_required = 75,
        hide_from_player_crafting = true,
        ingredients = {
            {type="item", name="par-fusion-reactor-mk7", amount=1},
            {type="item", name="sulfur", amount=50},
            {type="item", name="advanced-circuit", amount=100},
            {type="item", name="processing-unit", amount=100},
            {type="item", name="low-density-structure", amount=100},
        },
        results = {{type="item", name="par-fusion-reactor-mk8", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk9",
        enabled = false,
        energy_required = 80,
        hide_from_player_crafting = true,
        category = "crafting-with-fluid",
        ingredients = {
            {type="item", name="par-fusion-reactor-mk8", amount=1},
            {type="item", name="nuclear-fuel", amount=55},
            {type="item", name="processing-unit", amount=150},
            {type="item", name="armour-control-unit", amount=30},
            {type="item", name="low-density-structure", amount=250},
            {type="fluid", name="petroleum-gas", amount=200}
        },
        results = {{type="item", name="par-fusion-reactor-mk9", amount=1}},
    },
    {
        type = "recipe",
        name = "par-fusion-reactor-mk10",
        enabled = false,
        energy_required = 85,
        hide_from_player_crafting = true,
        ingredients = {
            {type="item", name="par-fusion-reactor-mk9", amount=1},
            {type="item", name="battery", amount=100},
            {type="item", name="processing-unit", amount=200},
            {type="item", name="armour-control-unit", amount=30},
            {type="item", name="low-density-structure", amount=250},
        },
        results = {{type="item", name="par-fusion-reactor-mk10", amount=1}},
    },
}
data:extend(recipes)