local Tech = data.raw["technology"]
if (mods["Krastorio2"] or mods["Krastorio2-spaced-out"]) then
	table.insert(Tech["par-armour-tech-5"].unit.ingredients, {"automation-science-pack", 4})
	table.insert(Tech["par-armour-tech-5"].unit.ingredients, {"logistic-science-pack",   3})
	table.insert(Tech["par-armour-tech-5"].unit.ingredients, {"military-science-pack",   2})
	table.insert(Tech["par-armour-tech-5"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-armour-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-armour-tech-6"].unit.ingredients, {"automation-science-pack", 5})
	table.insert(Tech["par-armour-tech-6"].unit.ingredients, {"logistic-science-pack",   4})
	table.insert(Tech["par-armour-tech-6"].unit.ingredients, {"military-science-pack",   3})
	table.insert(Tech["par-armour-tech-6"].unit.ingredients, {"chemical-science-pack",   2})
	table.insert(Tech["par-armour-tech-6"].unit.ingredients, {"kr-advanced-tech-card",   2})

	table.insert(Tech["par-armour-tech-7"].unit.ingredients, {"automation-science-pack",  6})
	table.insert(Tech["par-armour-tech-7"].unit.ingredients, {"logistic-science-pack",	  5})
	table.insert(Tech["par-armour-tech-7"].unit.ingredients, {"military-science-pack",    4})
	table.insert(Tech["par-armour-tech-7"].unit.ingredients, {"chemical-science-pack",    3})
	table.insert(Tech["par-armour-tech-7"].unit.ingredients, {"kr-advanced-tech-card",    2})
	table.insert(Tech["par-armour-tech-7"].unit.ingredients, {"kr-matter-tech-card", 	  1})
	table.insert(Tech["par-armour-tech-7"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-armour-tech-8"].unit.ingredients, {"automation-science-pack",  7})
	table.insert(Tech["par-armour-tech-8"].unit.ingredients, {"logistic-science-pack",    6})
	table.insert(Tech["par-armour-tech-8"].unit.ingredients, {"military-science-pack",	  5})
	table.insert(Tech["par-armour-tech-8"].unit.ingredients, {"chemical-science-pack",	  4})
	table.insert(Tech["par-armour-tech-8"].unit.ingredients, {"kr-advanced-tech-card",	  3})
	table.insert(Tech["par-armour-tech-8"].unit.ingredients, {"kr-matter-tech-card",	  2})
	table.insert(Tech["par-armour-tech-8"].unit.ingredients, {"kr-singularity-tech-card", 2})

	table.insert(Tech["par-armour-tech-9"].unit.ingredients, {"automation-science-pack",	8})
	table.insert(Tech["par-armour-tech-9"].unit.ingredients, {"logistic-science-pack",		7})
	table.insert(Tech["par-armour-tech-9"].unit.ingredients, {"military-science-pack",		6})
	table.insert(Tech["par-armour-tech-9"].unit.ingredients, {"chemical-science-pack",		5})
	table.insert(Tech["par-armour-tech-9"].unit.ingredients, {"kr-advanced-tech-card",		4})
	table.insert(Tech["par-armour-tech-9"].unit.ingredients, {"kr-matter-tech-card",		3})
	table.insert(Tech["par-armour-tech-9"].unit.ingredients, {"kr-singularity-tech-card",	3})

	table.insert(Tech["par-armour-tech-10"].unit.ingredients, {"automation-science-pack",	9})
	table.insert(Tech["par-armour-tech-10"].unit.ingredients, {"logistic-science-pack",		8})
	table.insert(Tech["par-armour-tech-10"].unit.ingredients, {"military-science-pack",		7})
	table.insert(Tech["par-armour-tech-10"].unit.ingredients, {"chemical-science-pack",		6})
	table.insert(Tech["par-armour-tech-10"].unit.ingredients, {"kr-advanced-tech-card",		5})
	table.insert(Tech["par-armour-tech-10"].unit.ingredients, {"kr-matter-tech-card",		4})
	table.insert(Tech["par-armour-tech-10"].unit.ingredients, {"kr-singularity-tech-card",  4})

	table.insert(Tech["par-exoskeleton-tech-3"].unit.ingredients, {"automation-science-pack", 1})
	table.insert(Tech["par-exoskeleton-tech-3"].unit.ingredients, {"logistic-science-pack",   1})
	table.insert(Tech["par-exoskeleton-tech-3"].unit.ingredients, {"military-science-pack",   1})
	table.insert(Tech["par-exoskeleton-tech-3"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-exoskeleton-tech-3"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-exoskeleton-tech-4"].unit.ingredients, {"automation-science-pack",  1})
	table.insert(Tech["par-exoskeleton-tech-4"].unit.ingredients, {"logistic-science-pack",    1})
	table.insert(Tech["par-exoskeleton-tech-4"].unit.ingredients, {"military-science-pack",    1})
	table.insert(Tech["par-exoskeleton-tech-4"].unit.ingredients, {"chemical-science-pack",    1})
	table.insert(Tech["par-exoskeleton-tech-4"].unit.ingredients, {"kr-advanced-tech-card",    1})
	table.insert(Tech["par-exoskeleton-tech-4"].unit.ingredients, {"kr-matter-tech-card",	   1})
	table.insert(Tech["par-exoskeleton-tech-4"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-exoskeleton-tech-5"].unit.ingredients, {"automation-science-pack", 	1})
	table.insert(Tech["par-exoskeleton-tech-5"].unit.ingredients, {"logistic-science-pack",   	1})
	table.insert(Tech["par-exoskeleton-tech-5"].unit.ingredients, {"military-science-pack",   	1})
	table.insert(Tech["par-exoskeleton-tech-5"].unit.ingredients, {"chemical-science-pack",   	1})
	table.insert(Tech["par-exoskeleton-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   	1})
	table.insert(Tech["par-exoskeleton-tech-5"].unit.ingredients, {"kr-matter-tech-card",	  	1})
	table.insert(Tech["par-exoskeleton-tech-5"].unit.ingredients, {"kr-singularity-tech-card", 	1})

	table.insert(Tech["par-night-immunity-tech-2"].unit.ingredients, {"automation-science-pack",  1})
	table.insert(Tech["par-night-immunity-tech-2"].unit.ingredients, {"logistic-science-pack",    1})
	table.insert(Tech["par-night-immunity-tech-2"].unit.ingredients, {"military-science-pack",    1})
	table.insert(Tech["par-night-immunity-tech-2"].unit.ingredients, {"chemical-science-pack",	  1})
	table.insert(Tech["par-night-immunity-tech-2"].unit.ingredients, {"kr-advanced-tech-card",    1})
	table.insert(Tech["par-night-immunity-tech-2"].unit.ingredients, {"kr-matter-tech-card",	  1})
	table.insert(Tech["par-night-immunity-tech-2"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-battery-tech-5"].unit.ingredients, {"automation-science-pack", 4})
	table.insert(Tech["par-battery-tech-5"].unit.ingredients, {"logistic-science-pack",   3})
	table.insert(Tech["par-battery-tech-5"].unit.ingredients, {"military-science-pack",   2})
	table.insert(Tech["par-battery-tech-5"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-battery-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-battery-tech-6"].unit.ingredients, {"automation-science-pack", 5})
	table.insert(Tech["par-battery-tech-6"].unit.ingredients, {"logistic-science-pack",   4})
	table.insert(Tech["par-battery-tech-6"].unit.ingredients, {"military-science-pack",   3})
	table.insert(Tech["par-battery-tech-6"].unit.ingredients, {"chemical-science-pack",   2})
	table.insert(Tech["par-battery-tech-6"].unit.ingredients, {"kr-advanced-tech-card",   2})

	table.insert(Tech["par-battery-tech-7"].unit.ingredients, {"automation-science-pack",  6})
	table.insert(Tech["par-battery-tech-7"].unit.ingredients, {"logistic-science-pack",	   5})
	table.insert(Tech["par-battery-tech-7"].unit.ingredients, {"military-science-pack",    4})
	table.insert(Tech["par-battery-tech-7"].unit.ingredients, {"chemical-science-pack",    3})
	table.insert(Tech["par-battery-tech-7"].unit.ingredients, {"kr-advanced-tech-card",    2})
	table.insert(Tech["par-battery-tech-7"].unit.ingredients, {"kr-matter-tech-card",	   1})
	table.insert(Tech["par-battery-tech-7"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-battery-tech-8"].unit.ingredients, {"automation-science-pack",  7})
	table.insert(Tech["par-battery-tech-8"].unit.ingredients, {"logistic-science-pack",    6})
	table.insert(Tech["par-battery-tech-8"].unit.ingredients, {"military-science-pack",    5})
	table.insert(Tech["par-battery-tech-8"].unit.ingredients, {"chemical-science-pack",    4})
	table.insert(Tech["par-battery-tech-8"].unit.ingredients, {"kr-advanced-tech-card",    3})
	table.insert(Tech["par-battery-tech-8"].unit.ingredients, {"kr-matter-tech-card",	   2})
	table.insert(Tech["par-battery-tech-8"].unit.ingredients, {"kr-singularity-tech-card", 2})

	table.insert(Tech["par-battery-tech-9"].unit.ingredients, {"automation-science-pack",  8})
	table.insert(Tech["par-battery-tech-9"].unit.ingredients, {"logistic-science-pack",    7})
	table.insert(Tech["par-battery-tech-9"].unit.ingredients, {"military-science-pack",    6})
	table.insert(Tech["par-battery-tech-9"].unit.ingredients, {"chemical-science-pack",    5})
	table.insert(Tech["par-battery-tech-9"].unit.ingredients, {"kr-advanced-tech-card",    4})
	table.insert(Tech["par-battery-tech-9"].unit.ingredients, {"kr-matter-tech-card",	   3})
	table.insert(Tech["par-battery-tech-9"].unit.ingredients, {"kr-singularity-tech-card", 3})

	table.insert(Tech["par-battery-tech-10"].unit.ingredients, {"automation-science-pack",  9})
	table.insert(Tech["par-battery-tech-10"].unit.ingredients, {"logistic-science-pack",    8})
	table.insert(Tech["par-battery-tech-10"].unit.ingredients, {"military-science-pack",    7})
	table.insert(Tech["par-battery-tech-10"].unit.ingredients, {"chemical-science-pack",    6})
	table.insert(Tech["par-battery-tech-10"].unit.ingredients, {"kr-advanced-tech-card",    5})
	table.insert(Tech["par-battery-tech-10"].unit.ingredients, {"kr-matter-tech-card",	    4})
	table.insert(Tech["par-battery-tech-10"].unit.ingredients, {"kr-singularity-tech-card", 4})

	table.insert(Tech["par-solar-panel-tech-5"].unit.ingredients, {"automation-science-pack", 4})
	table.insert(Tech["par-solar-panel-tech-5"].unit.ingredients, {"logistic-science-pack",   3})
	table.insert(Tech["par-solar-panel-tech-5"].unit.ingredients, {"military-science-pack",   2})
	table.insert(Tech["par-solar-panel-tech-5"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-solar-panel-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-solar-panel-tech-6"].unit.ingredients, {"automation-science-pack", 5})
	table.insert(Tech["par-solar-panel-tech-6"].unit.ingredients, {"logistic-science-pack",   4})
	table.insert(Tech["par-solar-panel-tech-6"].unit.ingredients, {"military-science-pack",   3})
	table.insert(Tech["par-solar-panel-tech-6"].unit.ingredients, {"chemical-science-pack",   2})
	table.insert(Tech["par-solar-panel-tech-6"].unit.ingredients, {"kr-advanced-tech-card",   2})

	table.insert(Tech["par-solar-panel-tech-7"].unit.ingredients, {"automation-science-pack",  6})
	table.insert(Tech["par-solar-panel-tech-7"].unit.ingredients, {"logistic-science-pack",	   5})
	table.insert(Tech["par-solar-panel-tech-7"].unit.ingredients, {"military-science-pack",    4})
	table.insert(Tech["par-solar-panel-tech-7"].unit.ingredients, {"chemical-science-pack",    3})
	table.insert(Tech["par-solar-panel-tech-7"].unit.ingredients, {"kr-advanced-tech-card",    3})
	table.insert(Tech["par-solar-panel-tech-7"].unit.ingredients, {"kr-matter-tech-card",	   1})
	table.insert(Tech["par-solar-panel-tech-7"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-solar-panel-tech-8"].unit.ingredients, {"automation-science-pack",  7})
	table.insert(Tech["par-solar-panel-tech-8"].unit.ingredients, {"logistic-science-pack",    6})
	table.insert(Tech["par-solar-panel-tech-8"].unit.ingredients, {"military-science-pack",    5})
	table.insert(Tech["par-solar-panel-tech-8"].unit.ingredients, {"chemical-science-pack",    4})
	table.insert(Tech["par-solar-panel-tech-8"].unit.ingredients, {"kr-advanced-tech-card",    4})
	table.insert(Tech["par-solar-panel-tech-8"].unit.ingredients, {"kr-matter-tech-card",	   2})
	table.insert(Tech["par-solar-panel-tech-8"].unit.ingredients, {"kr-singularity-tech-card", 2})

	table.insert(Tech["par-solar-panel-tech-9"].unit.ingredients, {"automation-science-pack",  8})
	table.insert(Tech["par-solar-panel-tech-9"].unit.ingredients, {"logistic-science-pack",    7})
	table.insert(Tech["par-solar-panel-tech-9"].unit.ingredients, {"military-science-pack",    6})
	table.insert(Tech["par-solar-panel-tech-9"].unit.ingredients, {"chemical-science-pack",    5})
	table.insert(Tech["par-solar-panel-tech-9"].unit.ingredients, {"kr-advanced-tech-card",    5})
	table.insert(Tech["par-solar-panel-tech-9"].unit.ingredients, {"kr-matter-tech-card",	   3})
	table.insert(Tech["par-solar-panel-tech-9"].unit.ingredients, {"kr-singularity-tech-card", 3})

	table.insert(Tech["par-solar-panel-tech-10"].unit.ingredients, {"automation-science-pack",  9})
	table.insert(Tech["par-solar-panel-tech-10"].unit.ingredients, {"logistic-science-pack",    8})
	table.insert(Tech["par-solar-panel-tech-10"].unit.ingredients, {"military-science-pack",    7})
	table.insert(Tech["par-solar-panel-tech-10"].unit.ingredients, {"chemical-science-pack",    6})
	table.insert(Tech["par-solar-panel-tech-10"].unit.ingredients, {"kr-advanced-tech-card",    6})
	table.insert(Tech["par-solar-panel-tech-10"].unit.ingredients, {"kr-matter-tech-card",	    4})
	table.insert(Tech["par-solar-panel-tech-10"].unit.ingredients, {"kr-singularity-tech-card", 4})

	table.insert(Tech["par-laser-tech-5"].unit.ingredients, {"automation-science-pack", 4})
	table.insert(Tech["par-laser-tech-5"].unit.ingredients, {"logistic-science-pack",   3})
	table.insert(Tech["par-laser-tech-5"].unit.ingredients, {"military-science-pack",   2})
	table.insert(Tech["par-laser-tech-5"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-laser-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-laser-tech-6"].unit.ingredients, {"automation-science-pack", 5})
	table.insert(Tech["par-laser-tech-6"].unit.ingredients, {"logistic-science-pack",   4})
	table.insert(Tech["par-laser-tech-6"].unit.ingredients, {"military-science-pack",   3})
	table.insert(Tech["par-laser-tech-6"].unit.ingredients, {"chemical-science-pack",   2})
	table.insert(Tech["par-laser-tech-6"].unit.ingredients, {"kr-advanced-tech-card",   2})

	table.insert(Tech["par-laser-tech-7"].unit.ingredients, {"automation-science-pack",  6})
	table.insert(Tech["par-laser-tech-7"].unit.ingredients, {"logistic-science-pack",	 5})
	table.insert(Tech["par-laser-tech-7"].unit.ingredients, {"military-science-pack",    4})
	table.insert(Tech["par-laser-tech-7"].unit.ingredients, {"chemical-science-pack",    3})
	table.insert(Tech["par-laser-tech-7"].unit.ingredients, {"kr-advanced-tech-card",    3})
	table.insert(Tech["par-laser-tech-7"].unit.ingredients, {"kr-matter-tech-card",	     1})
	table.insert(Tech["par-laser-tech-7"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-laser-tech-8"].unit.ingredients, {"automation-science-pack",  7})
	table.insert(Tech["par-laser-tech-8"].unit.ingredients, {"logistic-science-pack",    6})
	table.insert(Tech["par-laser-tech-8"].unit.ingredients, {"military-science-pack",    5})
	table.insert(Tech["par-laser-tech-8"].unit.ingredients, {"chemical-science-pack",    4})
	table.insert(Tech["par-laser-tech-8"].unit.ingredients, {"kr-advanced-tech-card",    4})
	table.insert(Tech["par-laser-tech-8"].unit.ingredients, {"kr-matter-tech-card",	     2})
	table.insert(Tech["par-laser-tech-8"].unit.ingredients, {"kr-singularity-tech-card", 2})

	table.insert(Tech["par-laser-tech-9"].unit.ingredients, {"automation-science-pack",  8})
	table.insert(Tech["par-laser-tech-9"].unit.ingredients, {"logistic-science-pack",    7})
	table.insert(Tech["par-laser-tech-9"].unit.ingredients, {"military-science-pack",    6})
	table.insert(Tech["par-laser-tech-9"].unit.ingredients, {"chemical-science-pack",    5})
	table.insert(Tech["par-laser-tech-9"].unit.ingredients, {"kr-advanced-tech-card",    5})
	table.insert(Tech["par-laser-tech-9"].unit.ingredients, {"kr-matter-tech-card",	     3})
	table.insert(Tech["par-laser-tech-9"].unit.ingredients, {"kr-singularity-tech-card", 3})

	table.insert(Tech["par-laser-tech-10"].unit.ingredients, {"automation-science-pack",  9})
	table.insert(Tech["par-laser-tech-10"].unit.ingredients, {"logistic-science-pack",    8})
	table.insert(Tech["par-laser-tech-10"].unit.ingredients, {"military-science-pack",    7})
	table.insert(Tech["par-laser-tech-10"].unit.ingredients, {"chemical-science-pack",    6})
	table.insert(Tech["par-laser-tech-10"].unit.ingredients, {"kr-advanced-tech-card",    6})
	table.insert(Tech["par-laser-tech-10"].unit.ingredients, {"kr-matter-tech-card",	  4})
	table.insert(Tech["par-laser-tech-10"].unit.ingredients, {"kr-singularity-tech-card", 4})

	table.insert(Tech["par-roboport-tech-5"].unit.ingredients, {"automation-science-pack", 4})
	table.insert(Tech["par-roboport-tech-5"].unit.ingredients, {"logistic-science-pack",   3})
	table.insert(Tech["par-roboport-tech-5"].unit.ingredients, {"military-science-pack",   2})
	table.insert(Tech["par-roboport-tech-5"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-roboport-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-roboport-tech-6"].unit.ingredients, {"automation-science-pack", 5})
	table.insert(Tech["par-roboport-tech-6"].unit.ingredients, {"logistic-science-pack",   4})
	table.insert(Tech["par-roboport-tech-6"].unit.ingredients, {"military-science-pack",   3})
	table.insert(Tech["par-roboport-tech-6"].unit.ingredients, {"chemical-science-pack",   2})
	table.insert(Tech["par-roboport-tech-6"].unit.ingredients, {"kr-advanced-tech-card",   2})

	table.insert(Tech["par-roboport-tech-7"].unit.ingredients, {"automation-science-pack",  6})
	table.insert(Tech["par-roboport-tech-7"].unit.ingredients, {"logistic-science-pack",	5})
	table.insert(Tech["par-roboport-tech-7"].unit.ingredients, {"military-science-pack",    4})
	table.insert(Tech["par-roboport-tech-7"].unit.ingredients, {"chemical-science-pack",    3})
	table.insert(Tech["par-roboport-tech-7"].unit.ingredients, {"kr-advanced-tech-card",    3})
	table.insert(Tech["par-roboport-tech-7"].unit.ingredients, {"kr-matter-tech-card",	    1})
	table.insert(Tech["par-roboport-tech-7"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-roboport-tech-8"].unit.ingredients, {"automation-science-pack",  7})
	table.insert(Tech["par-roboport-tech-8"].unit.ingredients, {"logistic-science-pack",    6})
	table.insert(Tech["par-roboport-tech-8"].unit.ingredients, {"military-science-pack",    5})
	table.insert(Tech["par-roboport-tech-8"].unit.ingredients, {"chemical-science-pack",    4})
	table.insert(Tech["par-roboport-tech-8"].unit.ingredients, {"kr-advanced-tech-card",    4})
	table.insert(Tech["par-roboport-tech-8"].unit.ingredients, {"kr-matter-tech-card",	    2})
	table.insert(Tech["par-roboport-tech-8"].unit.ingredients, {"kr-singularity-tech-card", 2})

	table.insert(Tech["par-roboport-tech-9"].unit.ingredients, {"automation-science-pack",  8})
	table.insert(Tech["par-roboport-tech-9"].unit.ingredients, {"logistic-science-pack",    7})
	table.insert(Tech["par-roboport-tech-9"].unit.ingredients, {"military-science-pack",    6})
	table.insert(Tech["par-roboport-tech-9"].unit.ingredients, {"chemical-science-pack",    5})
	table.insert(Tech["par-roboport-tech-9"].unit.ingredients, {"kr-advanced-tech-card",    5})
	table.insert(Tech["par-roboport-tech-9"].unit.ingredients, {"kr-matter-tech-card",	    3})
	table.insert(Tech["par-roboport-tech-9"].unit.ingredients, {"kr-singularity-tech-card", 3})

	table.insert(Tech["par-roboport-tech-10"].unit.ingredients, {"automation-science-pack",  9})
	table.insert(Tech["par-roboport-tech-10"].unit.ingredients, {"logistic-science-pack",    8})
	table.insert(Tech["par-roboport-tech-10"].unit.ingredients, {"military-science-pack",    7})
	table.insert(Tech["par-roboport-tech-10"].unit.ingredients, {"chemical-science-pack",    6})
	table.insert(Tech["par-roboport-tech-10"].unit.ingredients, {"kr-advanced-tech-card",    6})
	table.insert(Tech["par-roboport-tech-10"].unit.ingredients, {"kr-matter-tech-card",		 4})
	table.insert(Tech["par-roboport-tech-10"].unit.ingredients, {"kr-singularity-tech-card", 4})

	table.insert(Tech["par-shield-tech-5"].unit.ingredients, {"automation-science-pack", 4})
	table.insert(Tech["par-shield-tech-5"].unit.ingredients, {"logistic-science-pack",   3})
	table.insert(Tech["par-shield-tech-5"].unit.ingredients, {"military-science-pack",   2})
	table.insert(Tech["par-shield-tech-5"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-shield-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-shield-tech-6"].unit.ingredients, {"automation-science-pack", 5})
	table.insert(Tech["par-shield-tech-6"].unit.ingredients, {"logistic-science-pack",   4})
	table.insert(Tech["par-shield-tech-6"].unit.ingredients, {"military-science-pack",   3})
	table.insert(Tech["par-shield-tech-6"].unit.ingredients, {"chemical-science-pack",   2})
	table.insert(Tech["par-shield-tech-6"].unit.ingredients, {"kr-advanced-tech-card",   2})

	table.insert(Tech["par-shield-tech-7"].unit.ingredients, {"automation-science-pack",  6})
	table.insert(Tech["par-shield-tech-7"].unit.ingredients, {"logistic-science-pack",	  5})
	table.insert(Tech["par-shield-tech-7"].unit.ingredients, {"military-science-pack",    4})
	table.insert(Tech["par-shield-tech-7"].unit.ingredients, {"chemical-science-pack",    3})
	table.insert(Tech["par-shield-tech-7"].unit.ingredients, {"kr-advanced-tech-card",    3})
	table.insert(Tech["par-shield-tech-7"].unit.ingredients, {"kr-matter-tech-card",	  1})
	table.insert(Tech["par-shield-tech-7"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-shield-tech-8"].unit.ingredients, {"automation-science-pack",  7})
	table.insert(Tech["par-shield-tech-8"].unit.ingredients, {"logistic-science-pack",    6})
	table.insert(Tech["par-shield-tech-8"].unit.ingredients, {"military-science-pack",    5})
	table.insert(Tech["par-shield-tech-8"].unit.ingredients, {"chemical-science-pack",    4})
	table.insert(Tech["par-shield-tech-8"].unit.ingredients, {"kr-advanced-tech-card",    4})
	table.insert(Tech["par-shield-tech-8"].unit.ingredients, {"kr-matter-tech-card",	  2})
	table.insert(Tech["par-shield-tech-8"].unit.ingredients, {"kr-singularity-tech-card", 2})

	table.insert(Tech["par-shield-tech-9"].unit.ingredients, {"automation-science-pack",  8})
	table.insert(Tech["par-shield-tech-9"].unit.ingredients, {"logistic-science-pack",    7})
	table.insert(Tech["par-shield-tech-9"].unit.ingredients, {"military-science-pack",    6})
	table.insert(Tech["par-shield-tech-9"].unit.ingredients, {"chemical-science-pack",    5})
	table.insert(Tech["par-shield-tech-9"].unit.ingredients, {"kr-advanced-tech-card",    5})
	table.insert(Tech["par-shield-tech-9"].unit.ingredients, {"kr-matter-tech-card",	  3})
	table.insert(Tech["par-shield-tech-9"].unit.ingredients, {"kr-singularity-tech-card", 3})

	table.insert(Tech["par-shield-tech-10"].unit.ingredients, {"automation-science-pack",	9})
	table.insert(Tech["par-shield-tech-10"].unit.ingredients, {"logistic-science-pack",		8})
	table.insert(Tech["par-shield-tech-10"].unit.ingredients, {"military-science-pack",		7})
	table.insert(Tech["par-shield-tech-10"].unit.ingredients, {"chemical-science-pack",		6})
	table.insert(Tech["par-shield-tech-10"].unit.ingredients, {"kr-advanced-tech-card",		6})
	table.insert(Tech["par-shield-tech-10"].unit.ingredients, {"kr-matter-tech-card",		4})
	table.insert(Tech["par-shield-tech-10"].unit.ingredients, {"kr-singularity-tech-card",	4})

	table.insert(Tech["par-shock-defense-tech-5"].unit.ingredients, {"automation-science-pack", 4})
	table.insert(Tech["par-shock-defense-tech-5"].unit.ingredients, {"logistic-science-pack",   3})
	table.insert(Tech["par-shock-defense-tech-5"].unit.ingredients, {"military-science-pack",   2})
	table.insert(Tech["par-shock-defense-tech-5"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-shock-defense-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-shock-defense-tech-6"].unit.ingredients, {"automation-science-pack", 5})
	table.insert(Tech["par-shock-defense-tech-6"].unit.ingredients, {"logistic-science-pack",   4})
	table.insert(Tech["par-shock-defense-tech-6"].unit.ingredients, {"military-science-pack",   3})
	table.insert(Tech["par-shock-defense-tech-6"].unit.ingredients, {"chemical-science-pack",   2})
	table.insert(Tech["par-shock-defense-tech-6"].unit.ingredients, {"kr-advanced-tech-card",   2})

	table.insert(Tech["par-shock-defense-tech-7"].unit.ingredients, {"automation-science-pack",  6})
	table.insert(Tech["par-shock-defense-tech-7"].unit.ingredients, {"logistic-science-pack",	 5})
	table.insert(Tech["par-shock-defense-tech-7"].unit.ingredients, {"military-science-pack",    4})
	table.insert(Tech["par-shock-defense-tech-7"].unit.ingredients, {"chemical-science-pack",    3})
	table.insert(Tech["par-shock-defense-tech-7"].unit.ingredients, {"kr-advanced-tech-card",    3})
	table.insert(Tech["par-shock-defense-tech-7"].unit.ingredients, {"kr-matter-tech-card",		 1})
	table.insert(Tech["par-shock-defense-tech-7"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-shock-defense-tech-8"].unit.ingredients, {"automation-science-pack",  7})
	table.insert(Tech["par-shock-defense-tech-8"].unit.ingredients, {"logistic-science-pack",    6})
	table.insert(Tech["par-shock-defense-tech-8"].unit.ingredients, {"military-science-pack",    5})
	table.insert(Tech["par-shock-defense-tech-8"].unit.ingredients, {"chemical-science-pack",    4})
	table.insert(Tech["par-shock-defense-tech-8"].unit.ingredients, {"kr-advanced-tech-card",    4})
	table.insert(Tech["par-shock-defense-tech-8"].unit.ingredients, {"kr-matter-tech-card",		 2})
	table.insert(Tech["par-shock-defense-tech-8"].unit.ingredients, {"kr-singularity-tech-card", 2})

	table.insert(Tech["par-shock-defense-tech-9"].unit.ingredients, {"automation-science-pack",  8})
	table.insert(Tech["par-shock-defense-tech-9"].unit.ingredients, {"logistic-science-pack",    7})
	table.insert(Tech["par-shock-defense-tech-9"].unit.ingredients, {"military-science-pack",    6})
	table.insert(Tech["par-shock-defense-tech-9"].unit.ingredients, {"chemical-science-pack",    5})
	table.insert(Tech["par-shock-defense-tech-9"].unit.ingredients, {"kr-advanced-tech-card",    5})
	table.insert(Tech["par-shock-defense-tech-9"].unit.ingredients, {"kr-matter-tech-card",		 3})
	table.insert(Tech["par-shock-defense-tech-9"].unit.ingredients, {"kr-singularity-tech-card", 3})

	table.insert(Tech["par-shock-defense-tech-10"].unit.ingredients, {"automation-science-pack", 9})
	table.insert(Tech["par-shock-defense-tech-10"].unit.ingredients, {"logistic-science-pack",	 8})
	table.insert(Tech["par-shock-defense-tech-10"].unit.ingredients, {"military-science-pack",	 7})
	table.insert(Tech["par-shock-defense-tech-10"].unit.ingredients, {"chemical-science-pack",	 6})
	table.insert(Tech["par-shock-defense-tech-10"].unit.ingredients, {"kr-advanced-tech-card",	 6})
	table.insert(Tech["par-shock-defense-tech-10"].unit.ingredients, {"kr-matter-tech-card",	 4})
	table.insert(Tech["par-shock-defense-tech-10"].unit.ingredients, {"kr-singularity-tech-card",4})

	table.insert(Tech["par-fission-reactor-tech-5"].unit.ingredients, {"automation-science-pack", 4})
	table.insert(Tech["par-fission-reactor-tech-5"].unit.ingredients, {"logistic-science-pack",   3})
	table.insert(Tech["par-fission-reactor-tech-5"].unit.ingredients, {"military-science-pack",   2})
	table.insert(Tech["par-fission-reactor-tech-5"].unit.ingredients, {"chemical-science-pack",   1})
	table.insert(Tech["par-fission-reactor-tech-5"].unit.ingredients, {"kr-advanced-tech-card",   1})

	table.insert(Tech["par-fission-reactor-tech-6"].unit.ingredients, {"automation-science-pack", 5})
	table.insert(Tech["par-fission-reactor-tech-6"].unit.ingredients, {"logistic-science-pack",   4})
	table.insert(Tech["par-fission-reactor-tech-6"].unit.ingredients, {"military-science-pack",   3})
	table.insert(Tech["par-fission-reactor-tech-6"].unit.ingredients, {"chemical-science-pack",   2})
	table.insert(Tech["par-fission-reactor-tech-6"].unit.ingredients, {"kr-advanced-tech-card",   2})

	table.insert(Tech["par-fission-reactor-tech-7"].unit.ingredients, {"automation-science-pack",  6})
	table.insert(Tech["par-fission-reactor-tech-7"].unit.ingredients, {"logistic-science-pack",	   5})
	table.insert(Tech["par-fission-reactor-tech-7"].unit.ingredients, {"military-science-pack",    4})
	table.insert(Tech["par-fission-reactor-tech-7"].unit.ingredients, {"chemical-science-pack",    3})
	table.insert(Tech["par-fission-reactor-tech-7"].unit.ingredients, {"kr-advanced-tech-card",    3})
	table.insert(Tech["par-fission-reactor-tech-7"].unit.ingredients, {"kr-matter-tech-card",	   1})
	table.insert(Tech["par-fission-reactor-tech-7"].unit.ingredients, {"kr-singularity-tech-card", 1})

	table.insert(Tech["par-fission-reactor-tech-8"].unit.ingredients, {"automation-science-pack",   7})
	table.insert(Tech["par-fission-reactor-tech-8"].unit.ingredients, {"logistic-science-pack",     6})
	table.insert(Tech["par-fission-reactor-tech-8"].unit.ingredients, {"military-science-pack",     5})
	table.insert(Tech["par-fission-reactor-tech-8"].unit.ingredients, {"chemical-science-pack",     4})
	table.insert(Tech["par-fission-reactor-tech-8"].unit.ingredients, {"kr-advanced-tech-card",     4})
	table.insert(Tech["par-fission-reactor-tech-8"].unit.ingredients, {"kr-matter-tech-card",		2})
	table.insert(Tech["par-fission-reactor-tech-8"].unit.ingredients, {"kr-singularity-tech-card",  2})

	table.insert(Tech["par-fission-reactor-tech-9"].unit.ingredients, {"automation-science-pack",  8})
	table.insert(Tech["par-fission-reactor-tech-9"].unit.ingredients, {"logistic-science-pack",    7})
	table.insert(Tech["par-fission-reactor-tech-9"].unit.ingredients, {"military-science-pack",    6})
	table.insert(Tech["par-fission-reactor-tech-9"].unit.ingredients, {"chemical-science-pack",    5})
	table.insert(Tech["par-fission-reactor-tech-9"].unit.ingredients, {"kr-advanced-tech-card",    5})
	table.insert(Tech["par-fission-reactor-tech-9"].unit.ingredients, {"kr-matter-tech-card",	   3})
	table.insert(Tech["par-fission-reactor-tech-9"].unit.ingredients, {"kr-singularity-tech-card", 3})

	table.insert(Tech["par-fission-reactor-tech-10"].unit.ingredients, {"automation-science-pack",	9})
	table.insert(Tech["par-fission-reactor-tech-10"].unit.ingredients, {"logistic-science-pack",	8})
	table.insert(Tech["par-fission-reactor-tech-10"].unit.ingredients, {"military-science-pack",	7})
	table.insert(Tech["par-fission-reactor-tech-10"].unit.ingredients, {"chemical-science-pack",	6})
	table.insert(Tech["par-fission-reactor-tech-10"].unit.ingredients, {"kr-advanced-tech-card",	6})
	table.insert(Tech["par-fission-reactor-tech-10"].unit.ingredients, {"kr-matter-tech-card",		4})
	table.insert(Tech["par-fission-reactor-tech-10"].unit.ingredients, {"kr-singularity-tech-card",	4})
end